language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install

script:
  - vendor/bin/codecept run unit --coverage-xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  hipchat:
    rooms:
      secure: PNjDsKHLvJdZK+6naFMFk9elMicWzJEEs/a8Y1QgKPJY4SLeiV02EM+RmidppDxu2JUpj/QczTLfVkgKM6Ew9jdKjRLLqENctZIqhQzPQvKkSsxDiB2RNV6ahA9SfiWefQeXOsl04frBs7ZT405q9zFTyfldrvXVup1pBlh64lM=
